[model]
name = 'Config'
out_func = 'sigmod'
latent_dim = 128
backbone = 'sasrec'
c_num = 8
hid_dims = [128,256,128]

loss_func = 'ce'
dropout_ratio = 0.5
depth = 2
num_head = 4
exp_factor = 4
time_span = 256
max_seq_length = 64